name = "Iros"
uuid = "573aa7f4-91c9-40a8-9c96-241bf90c799c"
repo = "https://github.com/wrs28/Iros.jl.git"

[deps]
IrosBase = "dc165baa-4ec7-4ba6-9649-6ad7c8c72a04"
IrosFloquet = "325b1258-71f0-5f33-8884-69ee6b74aed3"
IrosSALT = "6e89c309-8aef-5d76-a55c-da59ac3a087f"
IrosSCPA = "ffc3f4d5-b14f-5bb7-8bcd-c8754cb9bf2d"
IrosScattering = "30a2cb00-b8a6-54dd-b9b8-72be8504d472"
IrosSpectral = "b2ce5262-62bd-11e9-037d-a93ccda198f7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
